Machine learning is mostly math on large datasets: vectors, matrices, tensors.
Python’s built-in lists are too slow and memory-heavy for that.
NumPy = Numerical Python → optimized for fast math operations on arrays, like linear algebra.

In [5]:
import numpy as np

##create array using numpy
##create 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [6]:
##reshaping the array into 2D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 1]]
(2, 5)


In [45]:
##SLICING
## [row:col,row:col]
##  include:not included

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr1)
print()
print(arr1[1:3,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 7  8]
 [12 13]]


In [44]:
##modify element
arr1[0,0]=100
print(arr1)

[[100   0   0   0   0]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [55]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

arr1[0:,1:]=0
arr1[1:,0]=0
print(arr1)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [56]:
##statistical concept- normalisation
##to have a mean and standard deviation of 1
data = np.array([1,2,3,4,5,6])

##calculate the mean and sd
mean = np.mean(data)
std_dev = np.std(data)

##normalise the data
normalised_data = (data-mean)/std_dev
print("Normalised data: ", normalised_data)

Normalised data:  [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [61]:
##logical opn
data = np.array([10,2345,211,4,5,6])
data[data<200]

data[(data>=100) & (data<25000)]

array([2345,  211])